# -*- coding: utf-8 -*-
"""example_py_code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JyMb0fFg7ecRle9QRu3eorbcRFU-hvuz
"""

print("Hello World")